CREATE OR REPLACE TABLE staging.customers_clean AS 
SELECT 
ID,
NAME,
GENDER,
TRY_TO_DATE(dateofbirth,'DD.MM.YY') AS dateofbirth,
EMAIL,
COALESCE(COUNTRY, 'Unknown') AS COUNTRY,
CITY,
TRY_TO_TIMESTAMP(created_at,'MM/DD/YYYY HH24:MI') AS created_at,
TRY_TO_TIMESTAMP(updated_at,'MM/DD/YYYY HH24:MI') AS updated_at
FROM raw.customers;

CREATE OR REPLACE TABLE staging.products_clean AS
SELECT 
ID,
NAME,
CODE,
CATEGORY,
PRICE,
CURRENCY,
INITCAP(COLOR) AS COLOR,
TRY_TO_TIMESTAMP(created_at,'MM/DD/YYYY HH24:MI') AS created_at,
TRY_TO_TIMESTAMP(updated_at,'MM/DD/YYYY HH24:MI') AS updated_at
FROM raw.products;

CREATE OR REPLACE TABLE staging.country_clean AS 
SELECT 
CODE,
NAME 
FROM raw.country;

CREATE OR REPLACE TABLE staging.sales_clean AS 
SELECT
CUSTOMER_ID,
PRODUCT_ID,
SALES_DATE,
COALESCE(QUANTITY, 0) AS QUANTITY,
COALESCE(TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT,
COALESCE(CURRENCY, 'UNKNOWN') AS CURRENCY,
TRY_TO_TIMESTAMP(created_at,'MM/DD/YYYY HH24:MI') AS created_at,
TRY_TO_TIMESTAMP(updated_at,'MM/DD/YYYY HH24:MI') AS updated_at
FROM raw.sales;

