ALTER WAREHOUSE compute_wh 
SET AUTO_SUSPEND = 60;

ALTER WAREHOUSE compute_wh 
SET AUTO_RESUME = TRUE;

ALTER WAREHOUSE compute_wh 
SET WAREHOUSE_SIZE = 'XSMALL';




ALTER USER adf_service_user
SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkugLgV6XXq6SkBTcbnyb
aBPurmFJR/tbv1+iaYw8WoG/AjOPcn5/SJQ7pAwDyDDticx/FIVKrUXS+rBYgNUp
mc/90mg4schnV4oAo6f4NihW79mmm3gFLkZKrByVkTE5nPpSY0V/JLZ5F/r0xp7r
bYGuJfiGimN5KmFLQTU83y3x/UVsxMZsWVnsclXpoKSJeOxHaUK4kan070OO8BL6
kCR8SdutRbSrmKca5p1SjJW4/gWkT4gg09EIULRuOOjoXOA0JjHhnF06OFmZ4i+c
MOgoDbgjxYE6nKYidyQmI2D6hQTeKe22Ebwuv7DAIJkNuI0lhAcXxen/Rk6fvV7s
cwIDAQAB';







