name: Snowflake Data Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  snowflake-deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli

      - name: Run Snowflake Commands
        env:
          PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > rsa_key.p8
          chmod 600 rsa_key.p8

          # Test Connection
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" -q "SELECT CURRENT_VERSION();"

          # 1_setup
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" -f snowflake/1_setup/01_create_database.sql

          # 2_create_schemas
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" -f snowflake/2_create_schemas/02_create_schemas.sql

          # 3_external_stage
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/3_external_stage/03_create_stage.sql
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/3_external_stage/04_create_file_format.sql

          # 4_metadata
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/4_metadata/05_create_logging_tables.sql
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/4_metadata/06_create_metadata_tables.sql
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/4_metadata/07_create_dq_results_tables.sql

          # 5_raw
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/5_raw/08_create_raw_tables.sql
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/5_raw/09_load_data_into_raw_tables.sql

          # 6_staging
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/6_staging/10_staging_transformations.sql

          # 7_data_quality
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/7_data_quality/11_data_quality_checks.sql

          # 8_analytics
          snow sql --temporary-connection --authenticator SNOWFLAKE_JWT --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USER" --private-key-path rsa_key.p8 --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" -f snowflake/8_analytics/12_analytics.sql

          rm rsa_key.p8

          